are_leapting:
  station: [
           {node_name: 'out', param: [44.44, 25.2, pre,in]},
           {node_name: 'in', param: [39.0, 25.2, out]},
          
          ]
#拓扑地图
  node_list: [
    {node_name: 't1',  param:   [46.5,  7.0339, t2,t10]},
    {node_name: 't2',  param:   [46.5, 14.2017, t1,t3]},
    {node_name: 't3',  param:   [46.5, 20.1648, t2,t4,pre]},
    {node_name: 't4',  param:   [46.5, 27.8747, t3,t5,pre]},
    {node_name: 't5',  param:   [46.5, 36.3129, t4,t6]},
    {node_name: 't6', param:    [82.0, 36.3129, t7,t5]},
    {node_name: 't7',  param:   [82.0, 27.8747, t6,t8]},
    {node_name: 't8',  param:   [82.0, 20.1648, t7,t9]},
    {node_name: 't9',  param:   [82.0, 14.2017, t8,t10]},
    {node_name: 't10',  param:  [82.0,  7.0339, t9,t1]},
    {node_name: 'pre', param:   [46.12,25.2, t3,t4]},
    
   ]
